/** User entity definition */
package io.zetch.app.domain.user;

import io.zetch.app.domain.BaseEntity;
import io.zetch.app.domain.restaurant.RestaurantEntity;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.NonNull;
import lombok.RequiredArgsConstructor;
import lombok.Setter;
import lombok.ToString;

@Getter
@Setter
@ToString
@RequiredArgsConstructor
@NoArgsConstructor
@AllArgsConstructor
@Builder
@Entity
@Table(name = "zetch_user") // "User" is a reserved keyword in some DBs
public class UserEntity extends BaseEntity {
  @NonNull
  @Column(unique = true)
  private String username;

  private Affiliation affiliation;
  private String displayName;
  private String email;

  // A restaurant might have multiple owners; a User might own multiple restaurants
  @ManyToMany(mappedBy = "owners")
  @ToString.Exclude
  private List<RestaurantEntity> ownedRestaurants;

  // TODO: List of posted reviews
  // @OneToMany
  // @ToString.Exclude
  // private List<Review> postedReviews;
  // TODO: List of posted replies (for restaurant owners)
  // @OneToMany
  // @ToString.Exclude
  // private List<Reply> postedReplies;

  /** Partial constructor that can't be generated by Lombok */
  public UserEntity(
      @NonNull String username, Affiliation affiliation, String displayName, String email) {
    this.username = username;
    this.affiliation = affiliation;
    this.displayName = displayName;
    this.email = email;
    this.ownedRestaurants = new ArrayList<>();
  }

  /**
   * Convert the User entity to a User data transfer object
   *
   * @return User DTO
   */
  public UserDto toDto() {
    return new UserDto(username, displayName, email, affiliation.toString());
  }
}
